[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/send-sms"
  to = "/.netlify/functions/send-sms"
  status = 200

[[redirects]]
  from = "/api/send-whatsapp"  
  to = "/.netlify/functions/send-whatsapp"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200